language: objective-c
osx_image: xcode9

before_script:
  - export LANG=en_US.UTF-8
script:
  - xcodebuild -project Stated.xcodeproj clean
  - travis_retry xcodebuild -project Stated.xcodeproj -scheme Stated -destination 'platform=iOS Simulator,name=iPhone 7' -configuration Debug test