matrix:
  include:
    # - language: objective-c
    #   osx_image: xcode9
    #   before_script:
    #     - export LANG=en_US.UTF-8

    #   script:
    #     - xcodebuild -project Stated.xcodeproj clean
    #     - travis_retry xcodebuild -project Stated.xcodeproj -scheme Stated-iOS -destination 'platform=iOS Simulator,name=iPhone 7' -configuration Debug test

    # - language: objective-c
    #   osx_image: xcode9
    #   before_script:
    #     - export LANG=en_US.UTF-8

    #   script:
    #     - xcodebuild -project Stated.xcodeproj clean
    #     - travis_retry xcodebuild -project Stated.xcodeproj -scheme Stated-macOS -configuration Debug test

    - language: generic
      os: linux
      sudo: required
      dist: trusty
      install:
        - ./install_swiftenv.sh
        - swiftenv install --list-snapshots
        - swiftenv install https://swift.org/builds/swift-4.0-release/ubuntu1404/swift-4.0-RELEASE/swift-4.0-RELEASE-ubuntu14.04.tar.gz
        - swift build

      script:
        - swift test